// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for suggesting a background theme based on mood.
 *
 * - suggestBackgroundTheme - The main function to suggest a background theme.
 * - SuggestBackgroundThemeInput - The input type for the suggestBackgroundTheme function.
 * - SuggestBackgroundThemeOutput - The output type for the suggestBackgroundTheme function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestBackgroundThemeInputSchema = z.object({
  mood: z.string().describe('The mood of the user (e.g., happy, sad, angry).'),
  moodType: z.string().describe('The category of the mood (e.g., Sad, Happy, Angry, In Love, Motivated, Lost, Confident, Depressed, Confused, Chill, Excited, Shy, Heartbroken, Dreamy)'),
});
export type SuggestBackgroundThemeInput = z.infer<typeof SuggestBackgroundThemeInputSchema>;

const SuggestBackgroundThemeOutputSchema = z.object({
  backgroundTheme: z.string().describe('A suggested background theme that matches the mood (e.g., neon purple haze, blue rainy gradient).'),
});
export type SuggestBackgroundThemeOutput = z.infer<typeof SuggestBackgroundThemeOutputSchema>;

export async function suggestBackgroundTheme(input: SuggestBackgroundThemeInput): Promise<SuggestBackgroundThemeOutput> {
  return suggestBackgroundThemeFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestBackgroundThemePrompt',
  input: {schema: SuggestBackgroundThemeInputSchema},
  output: {schema: SuggestBackgroundThemeOutputSchema},
  prompt: `Given the user's mood and mood type, suggest a background theme that would be aesthetically pleasing and viral for TikTok.

Mood: {{{mood}}}
Mood Type: {{{moodType}}}

Consider themes like "neon purple haze", "blue rainy gradient", "aesthetic sunset", "urban black-and-white", "glitchcore", "cozy pastel", "vaporwave". Pick the one that works best.

Background Theme: `,
});

const suggestBackgroundThemeFlow = ai.defineFlow(
  {
    name: 'suggestBackgroundThemeFlow',
    inputSchema: SuggestBackgroundThemeInputSchema,
    outputSchema: SuggestBackgroundThemeOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
